### PR TITLE
Compiler errors accessing `PuppeteerEnvironment` globals

### PR DESCRIPTION
**Pull request by colinrotherham**
## Summary

Fixes `PuppeteerEnvironment["global"]` types to resolve:

* https://github.com/argos-ci/jest-puppeteer/issues/548

I've also initialised `puppeteerConfig` and `jestPuppeteer` in the constructor as these are required

### CODE REVIEW

**Comment by gregberge** [comment]
@colinrotherham could you please rebase and fix linter? Thanks!

**Comment by colinrotherham** [comment]
@gregberge We found a workaround

The globals are extended in [**jest-puppeteer** `./src/index.ts`](https://github.com/argos-ci/jest-puppeteer/blob/main/packages/jest-puppeteer/src/index.ts) but we'd only installed **jest-environment-puppeteer**

This PR will need `jest-puppeteer` changes to identify `PuppeteerEnvironment` vs `NodeEnvironment` everywhere

NodeEnvironment extended

But for now we're sorted. Thanks again for a great tool 😊

**Comment by gregberge** [comment]
Hello @colinrotherham, I don't get it, is this PR still relevant or not?

**Comment by colinrotherham** [comment]
> Hello @colinrotherham, I don't get it, is this PR still relevant or not?

Yeah it's needed but I need your feedback please. This PR takes a different approach to the existing types

### ✅ Types for `PuppeteerEnvironment`
I've extended `PuppeteerEnvironment` in **jest-environment-puppeteer** to include `page`, `browser` globals etc
https://github.com/argos-ci/jest-puppeteer/blob/b26d07c30943ba74413e394dc9bdadee2542aee9/packages/jest-environment-puppeteer/src/env.ts#L133

### ❌ Types for `NodeEnvironment`

But in **jest-puppeteer** the existing types extend `NodeEnvironment` instead of `PuppeteerEnvironment`

This incorrectly identifies the `page` and `browser` globals on our Node and JSDOM environments too 😬

```ts
import { TestEnvironment } from 'jest-environment-node'

class NodeEnvironmentCustom extends TestEnvironment {
  async setup () {
    await super.setup()

    // These shouldn't be on NodeEnvironment
    this.global.page
    this.global.browser
  }
}
```

I'm not close enough to the project to understand what you'd prefer, or if this PR is good enough for now

Appreciate it

**Comment by gregberge** [comment]
@colinrotherham I think it is OK like that, thanks for the explanation; sorry for the delay!

**Pull request merged**
